### ISSUE TITLE
Feed time incorrect - showing based on last time any post was made

### ISSUE THREAD

**Issue by jpb5013** [stabledyne/issues#1]
After I made this post of Joe Hidin':

![image](https://github.com/stabledyne/issues/assets/11953835/d4f477b9-e024-423c-9f0c-fbe25f03e903)

The posted time on my post from yesterday about Dolan Rump reset to match the Joe Hidin post:

![image](https://github.com/stabledyne/issues/assets/11953835/f71a777b-a22b-413e-b9b2-ae5147c71295)

**Comment by jpb5013** [comment]
Actually, is feature? Add text? TBD.

**Comment by msoler8785** [comment]
was implemented long ago....
