### ISSUE TITLE
Move theme selector icon to profile

### ISSUE THREAD

**Issue by jpb5013** [stabledyne/issues#13]
![image](https://github.com/stabledyne/issues/assets/11953835/b99cad93-75c4-45c2-b9a6-e5629559ab26)

**Comment by msoler8785** [comment]
Moved to settings page: https://github.com/stabledyne/Stabledyne.WebApp/commit/1f4319a6aea16e3ab758deaa5ef18a2800b85a30#diff-fafc5b2596c1bfc0b6822180e7039475185d026b984a44a06be1c4f2be06b0d7
