### ISSUE TITLE
Make URL clicks open in separate tab

### ISSUE THREAD

**Issue by jpb5013** [stabledyne/issues#16]
As an example, the link from [this post](https://app.stabledyne.ai/feed/comments/08dc84d7-710b-42b8-8cd1-2d1acc7dca4e) opens in the existing tab.

Now, let's not be Facebook and make it impossible for people to hit back to exit the website.

**Comment by msoler8785** [comment]
Fixed: https://github.com/stabledyne/Stabledyne.WebApp/commit/1f4319a6aea16e3ab758deaa5ef18a2800b85a30#diff-fafc5b2596c1bfc0b6822180e7039475185d026b984a44a06be1c4f2be06b0d7
