### ISSUE TITLE
Hamburger menu doesn’t work on create post (mobile, iOS)

### ISSUE THREAD

**Issue by jpb5013** [stabledyne/issues#52]
As a dank content creator, I would like this to work

**Comment by msoler8785** [comment]
Look at this it looks like the hamburger menu does open, it's just underneath the create post. 

We have three options I think:

Is the expectation that it should open on top of the create post sidebar like this?
![image](https://github.com/user-attachments/assets/e6f6ade7-951c-4327-9442-3ae941edac51)
Or should we disable the hamburger menu?
Or should we close the post sidebar and open the hamburger menu?

I think the first one makes the most sense, but I'm not sure what the purpose of doing that would be.

**Comment by jpb5013** [comment]
I think the first option makes sense. I wanted to see a different community
the other day while I was making a post, so I think it’s helpful to be able
to navigate away and have a consistent UI, even while in pop outs.

On Fri, Oct 25, 2024 at 11:28 AM Matt Soler ***@***.***>
wrote:

> Look at this it looks like the hamburger menu does open, it's just
> underneath the create post.
>
> We have three options I think:
>
> Is the expectation that it should open on top of the create post sidebar
> like this?
> image.png (view on web)
> <https://github.com/user-attachments/assets/e6f6ade7-951c-4327-9442-3ae941edac51>
> Or should we disable the hamburger menu?
> Or should we close the post sidebar and open the hamburger
>

menu?

**Comment by msoler8785** [comment]
fixed
